import { ENUMS, configureEnumTranslation } from './enums.js';

const languageRefreshSubscribers = new Set();

function subscribeLanguageRefresh(listener) {
    if (typeof listener !== 'function') {
        throw new TypeError('Language refresh subscriber must be a function');
    }
    languageRefreshSubscribers.add(listener);
    return function unsubscribeLanguageRefresh() {
        languageRefreshSubscribers.delete(listener);
    };
}

function callGlobalCallback(name) {
    var callback = globalThis && globalThis[name];
    if (typeof callback === 'function') callback();
}

function notifyLanguageRefresh() {
    // These callbacks still belong to the classic application during the
    // transition. Resolve them at notification time so language changes work
    // before and after the legacy bundle has loaded.
    callGlobalCallback('renderCompanySwitcher');
    callGlobalCallback('refreshLocalizedNameViews');
    callGlobalCallback('billingRefreshUsageNotices');
    Array.from(languageRefreshSubscribers).forEach(function(listener) {
        listener(currentLang);
    });
}

    // KIT SLICE — regenerated by scripts/slice-i18n.mjs; the mechanism above
    // and below this literal is verbatim from the source file, the dictionary
    // is reduced to the 144 keys the extracted components reference.
    var I18N = {
        zh: {
            "admin.noResults": "沒有符合的結果",
            "common.allShown": "— 已顯示全部 —",
            "common.list.searchMatch": "，搜尋「{{q}}」匹配",
            "common.loadFail": "載入失敗",
            "common.loading": "載入中...",
            "common.refreshList": "刷新列表",
            "common.scrollMore": "滾動加載更多...",
            "auth.backLogin": "← 返回登錄",
            "auth.clickReset": "點擊重設密碼",
            "auth.confirmReset": "確認重設",
            "auth.forgotPwd": "忘記密碼？",
            "auth.forgotPwdSub": "輸入用戶名或已綁定的電郵地址，我們會發送重設鏈接",
            "auth.google": "使用 Google 登錄",
            "auth.invalidEmail": "請輸入有效電郵",
            "auth.noAccount": "還沒有帳號？",
            "auth.or": "或",
            "auth.password": "密碼",
            "auth.registerLink": "立即註冊",
            "auth.remember": "記住我",
            "auth.resetPwd": "重設密碼",
            "auth.resetPwdSub": "請輸入新密碼（至少6位）",
            "auth.sendReset": "發送重設鏈接",
            "auth.sub": "請登錄以繼續",
            "auth.submit": "登錄",
            "auth.title": "客戶盡職審查系統",
            "auth.username": "用戶名/電郵",
            "billing.adminTitle": "充值及退款審核",
            "billing.profileHint": "查看餘額、充值、退款和用量",
            "billing.title": "充值、退款與用量賬單",
            "changeRequest.pendingCount": "{{count}} 個待審批修改請求",
            "changeRequest.pendingDeleteNote": "正式資料尚未刪除；審批完成前此表單為唯讀。",
            "changeRequest.pendingDeleteTitle": "刪除請求正在等待審批",
            "changeRequest.pendingNote": "正式資料尚未改動；審批完成前此表單為唯讀。",
            "changeRequest.pendingSince": "提交於 {{time}}；正式資料尚未改動。",
            "changeRequest.pendingTitle": "修改請求正在等待審批",
            "changeRequest.requestDelete": "提交刪除請求",
            "changeRequest.title": "修改請求",
            "changeRequest.view": "查看請求",
            "client.f.addrBranch": "分行",
            "client.f.addrCorr": "通訊地址",
            "client.f.addrMain": "主營業地址",
            "client.f.addrOther": "其他",
            "client.f.addrTemp": "臨時營業地點",
            "client.saveConflict": "保存衝突：客戶資料已被他人修改，正在獲取最新數據...",
            "cm.loginToAccept": "請先登入或註冊，然後查看並接受公司邀請。",
            "cm.registerToAccept": "請使用受邀電郵註冊；登入後即可查看並接受邀請。",
            "common.back": "返回",
            "common.blank": "（空白）",
            "common.cancel": "取消",
            "common.cancelDraft": "取消草稿",
            "common.cancelDraftConfirm": "取消這份草稿？取消後不能復原。",
            "common.close": "關閉",
            "common.delete": "刪除",
            "common.draftAlreadyCancelled": "草稿已在其他操作中取消",
            "common.draftAlreadySubmitted": "草稿已在服務器正式提交，已恢復正式記錄",
            "common.draftCancelFail": "取消草稿失敗",
            "common.draftCancelled": "草稿已取消",
            "common.draftInvalidResponse": "服務器返回了無效的草稿資料",
            "common.draftSaveFail": "保存草稿失敗",
            "common.draftSaved": "草稿已安全保存；尚未正式提交",
            "common.draftSubmitFail": "正式提交失敗；草稿仍然保留",
            "common.draftSubmittedReloadFail": "草稿已正式提交，但無法重新載入正式記錄；請從列表重新開啟",
            "common.ok": "確定",
            "common.pullRefresh": "下拉刷新",
            "common.save": "保存",
            "common.savingDraft": "正在保存草稿…",
            "common.serverDraftNote": "只有你可以查看這份草稿；正式提交前不會出現在列表、計數或其他用戶的資料中。",
            "common.serverDraftTitle": "私人草稿",
            "common.submitFormal": "正式提交",
            "common.submitFormalConfirm": "正式提交後會創建業務記錄，草稿將不可再作為草稿編輯。確定提交嗎？",
            "common.submittedFormal": "已正式提交並創建記錄",
            "common.submittingFormal": "正在正式提交…",
            "ph.confirmPassword": "確認新密碼",
            "ph.currentPassword": "當前密碼",
            "ph.displayName": "輸入顯示名稱",
            "ph.newPassword": "輸入新密碼",
            "ph.newPasswordMin6": "新密碼（至少6位）",
            "ph.password": "輸入密碼",
            "ph.setupPassword": "設定密碼（至少4位）",
            "ph.setupPassword2": "再次輸入密碼",
            "ph.setupUsername": "設定用戶名",
            "ph.username": "輸入用戶名或電郵",
            "ph.usernameEmail": "輸入用戶名或電郵",
            "profile.aboutApp": "關於 CDD Screening",
            "profile.adminAudit": "平台審計記錄",
            "profile.adminCompanies": "公司資料",
            "profile.adminUsers": "系統用戶",
            "profile.bindEmail": "綁定電郵",
            "profile.changeAvatar": "更換頭像",
            "profile.changePassword": "修改密碼",
            "profile.chooseImage": "選擇圖片",
            "profile.displayName": "顯示名稱",
            "profile.editDisplayName": "編輯顯示名稱",
            "profile.editLoginName": "編輯登錄名稱",
            "profile.email": "綁定電郵",
            "profile.emailUnbound": "未綁定",
            "profile.emailUnverified": " (待驗證)",
            "profile.enterLoginName": "輸入登錄名稱（只含英文字母、數字、底線，2-30字符）",
            "profile.google": "Google 帳戶",
            "profile.googleLink": "連結 Google 帳戶",
            "profile.googleLinkConflictTitle": "無法連結 Google 帳戶",
            "profile.language": "語言偏好",
            "profile.languageEn": "English",
            "profile.languageZh": "繁體中文",
            "profile.logout": "登出",
            "profile.logoutConfirmTitle": "確認登出",
            "profile.logoutPwdMsg": "密碼已更新，是否要馬上登出並重新登錄？",
            "profile.myCompanies": "我的公司",
            "profile.password": "登錄密碼",
            "profile.passwordUnset": "（尚未設置）",
            "profile.save": "保存",
            "profile.saving": "正在保存...",
            "profile.sectionAbout": "關於",
            "profile.sectionAccount": "帳戶",
            "profile.sectionAdmin": "系統管理",
            "profile.sectionWorkspace": "工作空間",
            "profile.sendVerification": "發送驗證",
            "profile.settings": "系統設置",
            "profile.username": "登錄名稱",
            "reg.confirmPass": "確認密碼",
            "reg.confirmPassPh": "再次輸入密碼",
            "reg.email": "電郵地址",
            "reg.emailPh": "輸入電郵地址",
            "reg.password": "密碼",
            "reg.passwordPh": "設定密碼（至少4位）",
            "reg.sub": "創建您的帳號以開始使用",
            "reg.submit": "註冊並登錄",
            "reg.title": "註冊新帳號",
            "reg.username": "用戶名",
            "reg.usernamePh": "設定用戶名（至少2個字符）",
            "setup.adminPass": "管理員密碼",
            "setup.adminUser": "管理員用戶名",
            "setup.confirmPass": "確認密碼",
            "setup.sub": "創建管理員帳號",
            "setup.submit": "創建帳號並登錄",
            "setup.title": "首次設定",
            "terms.agree": "我同意",
            "terms.and": "及",
            "terms.privacy": "私隱政策",
            "terms.privacyBody": "本系統收集及處理的個人資料（包括但不限於客戶名稱、公司資料、身份證明文件、交易紀錄及審查紀錄）僅用於符合《打擊洗黑錢及恐怖分子籌資條例》（AMLO）及相關監管規定的客戶盡職審查（CDD）目的。所有資料均儲存於安全的雲端伺服器，並僅限獲授權人員存取。本公司承諾不會將您的個人資料用於未經授權的用途或轉交第三方，除非法律要求或獲得您的明確同意。",
            "terms.privacyTitle": "私隱政策",
            "terms.tos": "使用條款",
            "terms.tosBody": "使用本系統即表示您同意：\n\n1. 僅將本系統用於合法的客戶盡職審查及合規目的\n2. 妥善保管您的登錄憑證，不與他人共用\n3. 確保所輸入的客戶資料準確無誤\n4. 遵守所有適用的法律法規，包括但不限於《個人資料（私隱）條例》及AMLO\n5. 不進行任何可能危害系統安全或侵犯他人權利的行為\n\n本公司保留隨時修改本使用條款的權利，修改後的條款將於本系統公布時生效。",
            "terms.tosTitle": "使用條款",
        },
        en: {
            "admin.noResults": "No matching results",
            "common.allShown": "— All shown —",
            "common.list.searchMatch": ", matching \"{{q}}\"",
            "common.loadFail": "Load failed",
            "common.loading": "Loading...",
            "common.refreshList": "Refresh list",
            "common.scrollMore": "Scroll to load more...",
            "auth.backLogin": "← Back to Login",
            "auth.clickReset": "Click to reset password",
            "auth.confirmReset": "Confirm Reset",
            "auth.forgotPwd": "Forgot Password?",
            "auth.forgotPwdSub": "Enter your username or registered email address. We will send a reset link to your email.",
            "auth.google": "Continue with Google",
            "auth.invalidEmail": "Please enter a valid email",
            "auth.noAccount": "Don't have an account?",
            "auth.or": "or",
            "auth.password": "Password",
            "auth.registerLink": "Register now",
            "auth.remember": "Remember me",
            "auth.resetPwd": "Reset Password",
            "auth.resetPwdSub": "Enter your new password (at least 6 characters)",
            "auth.sendReset": "Send Reset Link",
            "auth.sub": "Please sign in to continue",
            "auth.submit": "Sign In",
            "auth.title": "Customer Due Diligence System",
            "auth.username": "Username / Email",
            "billing.adminTitle": "Top-up & Refund Review",
            "billing.profileHint": "View balance, top-ups, refunds and usage",
            "billing.title": "Top-ups, Refunds & Usage Billing",
            "changeRequest.pendingCount": "{{count}} pending change requests",
            "changeRequest.pendingDeleteNote": "The live record has not been deleted. This form is read-only until a decision is made.",
            "changeRequest.pendingDeleteTitle": "Deletion request awaiting approval",
            "changeRequest.pendingNote": "The live record is unchanged. This form is read-only until a decision is made.",
            "changeRequest.pendingSince": "Submitted {{time}}; the live record is unchanged.",
            "changeRequest.pendingTitle": "Change request awaiting approval",
            "changeRequest.requestDelete": "Submit deletion request",
            "changeRequest.title": "Change Requests",
            "changeRequest.view": "View request",
            "client.f.addrBranch": "Branch",
            "client.f.addrCorr": "Correspondence",
            "client.f.addrMain": "Main Address",
            "client.f.addrOther": "Other",
            "client.f.addrTemp": "Temporary Premise",
            "client.saveConflict": "Save conflict: client data was modified by another user, fetching latest...",
            "cm.loginToAccept": "Please sign in or register first, then review and accept the company invitation.",
            "cm.registerToAccept": "Register with the invited email. You can review and accept the invitation after signing in.",
            "common.back": "Back",
            "common.blank": "(blank)",
            "common.cancel": "Cancel",
            "common.cancelDraft": "Cancel Draft",
            "common.cancelDraftConfirm": "Cancel this draft? It cannot be restored.",
            "common.close": "Close",
            "common.delete": "Delete",
            "common.draftAlreadyCancelled": "The draft was cancelled by another operation",
            "common.draftAlreadySubmitted": "The draft was already submitted; the formal record has been restored",
            "common.draftCancelFail": "Failed to cancel draft",
            "common.draftCancelled": "Draft cancelled",
            "common.draftInvalidResponse": "The server returned invalid draft data",
            "common.draftSaveFail": "Failed to save draft",
            "common.draftSaved": "Draft saved safely; it has not been formally submitted",
            "common.draftSubmitFail": "Submission failed; the draft is still preserved",
            "common.draftSubmittedReloadFail": "The draft was submitted, but the formal record could not be reloaded; reopen it from the list",
            "common.ok": "OK",
            "common.pullRefresh": "Pull to refresh",
            "common.save": "Save",
            "common.savingDraft": "Saving draft…",
            "common.serverDraftNote": "Only you can view this draft. It is excluded from lists, counts, and other users until formal submission.",
            "common.serverDraftTitle": "Private draft",
            "common.submitFormal": "Submit",
            "common.submitFormalConfirm": "Submitting will create the formal business record and this draft can no longer be edited as a draft. Continue?",
            "common.submittedFormal": "Submitted and formal record created",
            "common.submittingFormal": "Submitting…",
            "ph.confirmPassword": "Confirm new password",
            "ph.currentPassword": "Current password",
            "ph.displayName": "Enter display name",
            "ph.newPassword": "Enter new password",
            "ph.newPasswordMin6": "New password (min 6 chars)",
            "ph.password": "Enter password",
            "ph.setupPassword": "Set password (min 4 chars)",
            "ph.setupPassword2": "Re-enter password",
            "ph.setupUsername": "Set username",
            "ph.username": "Enter username or email",
            "ph.usernameEmail": "Enter username or email",
            "profile.aboutApp": "About CDD Screening",
            "profile.adminAudit": "Platform Audit Trail",
            "profile.adminCompanies": "Company Data",
            "profile.adminUsers": "System Users",
            "profile.bindEmail": "Bind Email",
            "profile.changeAvatar": "Change avatar",
            "profile.changePassword": "Change Password",
            "profile.chooseImage": "Choose image",
            "profile.displayName": "Display Name",
            "profile.editDisplayName": "Edit Display Name",
            "profile.editLoginName": "Edit Login Name",
            "profile.email": "Email",
            "profile.emailUnbound": "Not bound",
            "profile.emailUnverified": " (unverified)",
            "profile.enterLoginName": "Enter login name (letters, digits, underscore only; 2-30 chars)",
            "profile.google": "Google Account",
            "profile.googleLink": "Link Google account",
            "profile.googleLinkConflictTitle": "Unable to link Google account",
            "profile.language": "Language",
            "profile.languageEn": "English",
            "profile.languageZh": "繁體中文",
            "profile.logout": "Logout",
            "profile.logoutConfirmTitle": "Confirm Logout",
            "profile.logoutPwdMsg": "Password updated. Log out now and sign in again?",
            "profile.myCompanies": "My Companies",
            "profile.password": "Password",
            "profile.passwordUnset": "(Not set)",
            "profile.save": "Save",
            "profile.saving": "Saving...",
            "profile.sectionAbout": "About",
            "profile.sectionAccount": "Account",
            "profile.sectionAdmin": "System Administration",
            "profile.sectionWorkspace": "Workspace",
            "profile.sendVerification": "Send verification",
            "profile.settings": "System Settings",
            "profile.username": "Username",
            "reg.confirmPass": "Confirm password",
            "reg.confirmPassPh": "Re-enter your password",
            "reg.email": "Email address",
            "reg.emailPh": "Enter your email address",
            "reg.password": "Password",
            "reg.passwordPh": "Set a password (at least 4 characters)",
            "reg.sub": "Create your account to get started",
            "reg.submit": "Register & sign in",
            "reg.title": "Create Account",
            "reg.username": "Username",
            "reg.usernamePh": "Choose a username (at least 2 characters)",
            "setup.adminPass": "Admin password",
            "setup.adminUser": "Admin username",
            "setup.confirmPass": "Confirm password",
            "setup.sub": "Create an admin account",
            "setup.submit": "Create account & sign in",
            "setup.title": "Initial Setup",
            "terms.agree": "I agree to the",
            "terms.and": "and",
            "terms.privacy": "Privacy Policy",
            "terms.privacyBody": "The personal data collected and processed by this system (including but not limited to client names, company information, identification documents, transaction records, and review records) is used solely for Customer Due Diligence (CDD) purposes in compliance with the Anti-Money Laundering and Counter-Terrorist Financing Ordinance (AMLO) and related regulatory requirements. All data is stored on secure cloud servers and accessible only to authorized personnel. We will not use your personal data for unauthorized purposes or disclose it to third parties unless required by law or with your explicit consent.",
            "terms.privacyTitle": "Privacy Policy",
            "terms.tos": "Terms of Service",
            "terms.tosBody": "By using this system, you agree to:\n\n1. Use the system solely for lawful customer due diligence and compliance purposes\n2. Keep your login credentials secure and not share them with others\n3. Ensure the accuracy of all client data entered\n4. Comply with all applicable laws and regulations, including but not limited to the Personal Data (Privacy) Ordinance and AMLO\n5. Refrain from any activity that may compromise system security or infringe on others' rights\n\nWe reserve the right to modify these terms at any time, effective upon posting on this system.",
            "terms.tosTitle": "Terms of Service",
        }
    };

    // 當前語言：detection (localStorage, navigator) lives at the application
    // boundary now — main.js runs ui/i18n-dom.js's detectLanguage() at boot and
    // hands the result to initLanguage(). The default is the classic fallback.
    var currentLang = 'zh';

    function normalizeLang(lang) {
        return lang === 'en' ? 'en' : 'zh';
    }

    // The boot-time assignment: no side effects, no notification — exactly
    // what the old module-load detection did.
    function initLanguage(lang) {
        currentLang = normalizeLang(lang);
    }

    // The DOM/persistence half of a language change registers here
    // (ui/i18n-dom.js). Core stays portable, and the classic ordering holds:
    // side effects run before subscribers hear about the change.
    var languageEffects = null;
    function setLanguageEffects(effects) {
        languageEffects = typeof effects === 'function' ? effects : null;
    }

    function setLang(lang) {
        currentLang = normalizeLang(lang);
        if (languageEffects) languageEffects(currentLang);
        notifyLanguageRefresh();
    }

    function t(key, vars) {
        var dict = I18N[currentLang] || I18N.zh;
        var s = dict[key];
        if (s === undefined) s = I18N.zh[key];
        if (s === undefined) s = key;
        if (vars) { for (var k in vars) { if (vars.hasOwnProperty(k)) s = s.split('{{' + k + '}}').join(vars[k] == null ? '' : vars[k]); } }
        return s;
    }
    configureEnumTranslation(t);

    // One display-name rule for the whole UI: a single name shown to the user
    // follows the selected UI language, then falls back to the other language.
    // Keep this separate from form widgets, which intentionally show/edit both
    // stored values.
    function fLocalizedName(nameCN, nameEN, fallback) {
        var cn = nameCN == null ? '' : String(nameCN).trim();
        var en = nameEN == null ? '' : String(nameEN).trim();
        var other = fallback == null ? '' : String(fallback).trim();
        return currentLang === 'en' ? (en || cn || other) : (cn || en || other);
    }
    function fIsIndividualClientType(clientType) {
        return clientType === ENUMS.CLIENT_TYPE.INDIVIDUAL || clientType === 'INDIVIDUAL';
    }
    function fLocalizedClientName(client, fallback) {
        if (!client) return fallback || '—';
        var type = client.clientType || client._clientType || client.client_type;
        // Client records, immutable review snapshots and transaction JOIN
        // metadata use different containers for the same semantic values.
        // Normalize all three here so every list follows one display rule.
        var companyCN = client.companyNameCN || client.clientCompanyNameCN || client.company_name_cn || client._clientCompanyNameCN || '';
        var companyEN = client.companyNameEN || client.clientCompanyNameEN || client.company_name_en || client._clientCompanyNameEN || '';
        var personCN = client.directorNameCN || client.directorNameCn || client.director_name_cn || client._clientNameCN || client._clientNameCn || '';
        var personEN = client.directorNameEN || client.directorNameEn || client.director_name_en || client._clientNameEN || client._clientNameEn || '';
        if (fIsIndividualClientType(type)) {
            return fLocalizedName(personCN, personEN, fLocalizedName(companyCN, companyEN, fallback));
        }
        return fLocalizedName(companyCN, companyEN, fLocalizedName(personCN, personEN, fallback));
    }

const i18nCompatibilityApi = {
    t,
    fLocalizedName,
    fIsIndividualClientType,
    fLocalizedClientName,
    setLang,
};

function installI18nCompatibility(target) {
    if (!target || (typeof target !== 'object' && typeof target !== 'function')) {
        throw new TypeError('i18n compatibility requires a global-like target');
    }
    Object.assign(target, i18nCompatibilityApi);
    Object.defineProperty(target, 'currentLang', {
        configurable: true,
        enumerable: true,
        get: function() { return currentLang; },
        set: function(lang) { setLang(lang); },
    });
    return target;
}

export {
    I18N,
    currentLang,
    initLanguage,
    setLanguageEffects,
    t,
    fLocalizedName,
    fIsIndividualClientType,
    fLocalizedClientName,
    setLang,
    subscribeLanguageRefresh,
    installI18nCompatibility,
};
